// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum AcademyMessageConditions : int
{
  None = 0,
  FavorRankUp = 1,
  AcademySchedule = 2,
  Answer = 3,
  Feedback = 4,
};


}
