// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ArenaSimulatorServer : int
{
  Preset = 0,
  Live = 1,
  Dev = 2,
  QA = 3,
};


}
