// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ArmorType : int
{
  LightArmor = 0,
  HeavyArmor = 1,
  Unarmed = 2,
  Structure = 3,
  Normal = 4,
  ElasticArmor = 5,
};


}
