// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum AttackType : int
{
  Single = 0,
  Splash = 1,
  Through = 2,
  Heal = 3,
};


}
