// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum AttendanceType : int
{
  Basic = 0,
  Event = 1,
  Newbie = 2,
  EventCountDown = 3,
  Event20Days = 4,
};


}
