// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum BattleCalculationStat : int
{
  FinalDamage = 0,
  FinalHeal = 1,
  FinalDamageRatio = 2,
  FinalDamageRatio2 = 3,
  FinalCriticalRate = 4,
};


}
