// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum BillingTransactionEndType : int
{
  None = 0,
  Success = 1,
  Cancel = 2,
};


}
