// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum BubbleType : int
{
  Idle = 0,
  Monologue = 1,
  EmoticonNormal = 2,
  EmoticonFavorite = 3,
  EmoticonReward = 4,
  EmoticonGiveGift = 5,
};


}
