// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum BuffConditionType : int
{
  All = 0,
  Character = 1,
  School = 2,
  Weapon = 3,
};


}
