// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum BuffOverlap : int
{
  Able = 0,
  Unable = 1,
  Change = 2,
  Additive = 3,
};


}
