// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ClanRewardType : int
{
  None = 0,
  AssistTerm = 1,
  AssistRent = 2,
  Attendance = 3,
};


}
