// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct ClearDeckRuleExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static ClearDeckRuleExcel GetRootAsClearDeckRuleExcel(ByteBuffer _bb) { return GetRootAsClearDeckRuleExcel(_bb, new ClearDeckRuleExcel()); }
  public static ClearDeckRuleExcel GetRootAsClearDeckRuleExcel(ByteBuffer _bb, ClearDeckRuleExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ClearDeckRuleExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Plana.FlatData.ContentType ContentType_ { get { int o = __p.__offset(4); return o != 0 ? (Plana.FlatData.ContentType)__p.bb.GetInt(o + __p.bb_pos) : Plana.FlatData.ContentType.None; } }
  public long SizeLimit { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Plana.FlatData.ClearDeckRuleExcel> CreateClearDeckRuleExcel(FlatBufferBuilder builder,
      Plana.FlatData.ContentType ContentType_ = Plana.FlatData.ContentType.None,
      long SizeLimit = 0) {
    builder.StartTable(2);
    ClearDeckRuleExcel.AddSizeLimit(builder, SizeLimit);
    ClearDeckRuleExcel.AddContentType_(builder, ContentType_);
    return ClearDeckRuleExcel.EndClearDeckRuleExcel(builder);
  }

  public static void StartClearDeckRuleExcel(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddContentType_(FlatBufferBuilder builder, Plana.FlatData.ContentType contentType_) { builder.AddInt(0, (int)contentType_, 0); }
  public static void AddSizeLimit(FlatBufferBuilder builder, long sizeLimit) { builder.AddLong(1, sizeLimit, 0); }
  public static Offset<Plana.FlatData.ClearDeckRuleExcel> EndClearDeckRuleExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.ClearDeckRuleExcel>(o);
  }
  public ClearDeckRuleExcelT UnPack() {
    var _o = new ClearDeckRuleExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ClearDeckRuleExcelT _o) {
        byte[] key = TableEncryptionService.CreateKey("ClearDeckRule");
    _o.ContentType_ = TableEncryptionService.Convert(this.ContentType_, key);
    _o.SizeLimit = TableEncryptionService.Convert(this.SizeLimit, key);
  }
  public static Offset<Plana.FlatData.ClearDeckRuleExcel> Pack(FlatBufferBuilder builder, ClearDeckRuleExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.ClearDeckRuleExcel>);
    return CreateClearDeckRuleExcel(
      builder,
      _o.ContentType_,
      _o.SizeLimit);
  }
}

public class ClearDeckRuleExcelT
{
  public Plana.FlatData.ContentType ContentType_ { get; set; }
  public long SizeLimit { get; set; }

  public ClearDeckRuleExcelT() {
    this.ContentType_ = Plana.FlatData.ContentType.None;
    this.SizeLimit = 0;
  }
}


static public class ClearDeckRuleExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ContentType_*/, 4 /*Plana.FlatData.ContentType*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*SizeLimit*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
