// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum ConquestProgressType : int
{
  None = 0,
  Upgrade = 1,
  Manage = 2,
};


}
