// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ConquestEventType : int
{
  None = 0,
  Event01 = 1,
  Event02 = 2,
};


}
