// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ConquestErosionType : int
{
  None = 0,
  IndividualErosion = 1,
  MassErosion = 2,
};


}
