// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ConquestTeamType : int
{
  None = 0,
  Team1 = 1,
  Team2 = 2,
  Team3 = 3,
};


}
