// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ContentsChangeType : int
{
  None = 0,
  WorldRaidBossDamageRatio = 1,
  WorldRaidBossGroupDate = 2,
};


}
