// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum CoverMotionType : int
{
  All = 0,
  Kneel = 1,
};


}
