// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum CurrencyOverChargeType : int
{
  CanNotCharge = 0,
  FitToLimit = 1,
  ChargeOverLimit = 2,
};


}
