// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum CVExceptionTarget : int
{
  CharacterId = 0,
  SquadType = 1,
};


}
