// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum CVUnlockScenarioType : int
{
  Main = 0,
  Event = 1,
  SpecialOperation = 2,
};


}
