// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum DialogType : int
{
  Talk = 0,
  Think = 1,
  UITalk = 2,
};


}
