// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum EmblemDisplayType : int
{
  Always = 0,
  Time = 1,
  Favor = 2,
  Potential = 3,
};


}
