// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum EmoticonEvent : int
{
  CoverEnter = 0,
  ShelterEnter = 1,
  Panic = 2,
  NearlyDead = 3,
  Reload = 4,
  Found = 5,
  GetBeacon = 6,
  Warning = 7,
};


}
