// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum EntityMaterialType : int
{
  Wood = 0,
  Stone = 1,
  Flesh = 2,
  Metal = 3,
};


}
