// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum EventContentDiceRaceNodeType : int
{
  StartNode = 0,
  RewardNode = 1,
  MoveForwardNode = 2,
  SpecialRewardNode = 3,
};


}
