// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum EventTargetType : int
{
  WeekDungeon = 0,
  Chaser = 1,
  Campaign_Normal = 2,
  Campaign_Hard = 3,
  SchoolDungeon = 4,
  AcademySchedule = 5,
  TimeAttackDungeon = 6,
  AccountLevelExpIncrease = 7,
  Raid = 8,
  EliminateRaid = 9,
};


}
