// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum EventNotifyType : int
{
  RewardIncreaseEvent = 0,
  AccountExpIncreaseEvent = 1,
  RaidSeasonManager = 2,
  TimeAttackDungeonSeasonManage = 3,
  EliminateRaidSeasonManage = 4,
};


}
