// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum EventContentReleaseType : int
{
  None = 0,
  Permanent = 1,
  MainStory = 2,
  PermanentSpecialOperate = 3,
  PermanentConquest = 4,
};


}
