// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum FieldTutorialType : int
{
  None = 0,
  MasteryHUD = 1,
  QuestHUD = 2,
  WorldMapHUD = 3,
};


}
