// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum FieldConditionType : int
{
  Invalid = 0,
  Interaction = 1,
  QuestInProgress = 2,
  QuestClear = 3,
  Date = 4,
  StageClear = 5,
  HasKeyword = 6,
  HasEvidence = 7,
  OpenDate = 8,
  OpenDateAfter = 9,
};


}
