// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum FormationLine : int
{
  Students = 0,
  TSS = 1,
};


}
