// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum FurnitureLocation : int
{
  None = 0,
  Inventory = 1,
  Floor = 2,
  WallLeft = 3,
  WallRight = 4,
};


}
