// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum FurnitureCategory : int
{
  Furnitures = 0,
  Decorations = 1,
  Interiors = 2,
};


}
