// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum Geas : int
{
  ForwardProjectile = 0,
  DiagonalProjectile = 1,
  SideProjectile = 2,
  Pierce = 3,
  Reflect = 4,
  Burn = 5,
  Chill = 6,
  AttackPower = 7,
  AttackSpeed = 8,
  Critical = 9,
  Heal = 10,
};


}
