// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum GroundNodeType : int
{
  None = 0,
  WalkAble = 1,
  JumpAble = 2,
  TSSOnly = 3,
  NotWalkAble = 2147483647,
};


}
