// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum GuideMissionTabType : int
{
  None = 0,
  Daily = 1,
  StageClear = 2,
};


}
