// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct LocalizeEtcExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static LocalizeEtcExcel GetRootAsLocalizeEtcExcel(ByteBuffer _bb) { return GetRootAsLocalizeEtcExcel(_bb, new LocalizeEtcExcel()); }
  public static LocalizeEtcExcel GetRootAsLocalizeEtcExcel(ByteBuffer _bb, LocalizeEtcExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LocalizeEtcExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Key { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public string NameKr { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameKrBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameKrBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameKrArray() { return __p.__vector_as_array<byte>(6); }
  public string DescriptionKr { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionKrBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetDescriptionKrBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetDescriptionKrArray() { return __p.__vector_as_array<byte>(8); }
  public string NameJp { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameJpBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameJpBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameJpArray() { return __p.__vector_as_array<byte>(10); }
  public string DescriptionJp { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionJpBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetDescriptionJpBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetDescriptionJpArray() { return __p.__vector_as_array<byte>(12); }
  public string NameTh { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameThBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetNameThBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetNameThArray() { return __p.__vector_as_array<byte>(14); }
  public string DescriptionTh { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionThBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetDescriptionThBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetDescriptionThArray() { return __p.__vector_as_array<byte>(16); }
  public string NameTw { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameTwBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetNameTwBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetNameTwArray() { return __p.__vector_as_array<byte>(18); }
  public string DescriptionTw { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionTwBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetDescriptionTwBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetDescriptionTwArray() { return __p.__vector_as_array<byte>(20); }
  public string NameEn { get { int o = __p.__offset(22); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameEnBytes() { return __p.__vector_as_span<byte>(22, 1); }
#else
  public ArraySegment<byte>? GetNameEnBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public byte[] GetNameEnArray() { return __p.__vector_as_array<byte>(22); }
  public string DescriptionEn { get { int o = __p.__offset(24); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionEnBytes() { return __p.__vector_as_span<byte>(24, 1); }
#else
  public ArraySegment<byte>? GetDescriptionEnBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public byte[] GetDescriptionEnArray() { return __p.__vector_as_array<byte>(24); }

  public static Offset<Plana.FlatData.LocalizeEtcExcel> CreateLocalizeEtcExcel(FlatBufferBuilder builder,
      uint Key = 0,
      StringOffset NameKrOffset = default(StringOffset),
      StringOffset DescriptionKrOffset = default(StringOffset),
      StringOffset NameJpOffset = default(StringOffset),
      StringOffset DescriptionJpOffset = default(StringOffset),
      StringOffset NameThOffset = default(StringOffset),
      StringOffset DescriptionThOffset = default(StringOffset),
      StringOffset NameTwOffset = default(StringOffset),
      StringOffset DescriptionTwOffset = default(StringOffset),
      StringOffset NameEnOffset = default(StringOffset),
      StringOffset DescriptionEnOffset = default(StringOffset)) {
    builder.StartTable(11);
    LocalizeEtcExcel.AddDescriptionEn(builder, DescriptionEnOffset);
    LocalizeEtcExcel.AddNameEn(builder, NameEnOffset);
    LocalizeEtcExcel.AddDescriptionTw(builder, DescriptionTwOffset);
    LocalizeEtcExcel.AddNameTw(builder, NameTwOffset);
    LocalizeEtcExcel.AddDescriptionTh(builder, DescriptionThOffset);
    LocalizeEtcExcel.AddNameTh(builder, NameThOffset);
    LocalizeEtcExcel.AddDescriptionJp(builder, DescriptionJpOffset);
    LocalizeEtcExcel.AddNameJp(builder, NameJpOffset);
    LocalizeEtcExcel.AddDescriptionKr(builder, DescriptionKrOffset);
    LocalizeEtcExcel.AddNameKr(builder, NameKrOffset);
    LocalizeEtcExcel.AddKey(builder, Key);
    return LocalizeEtcExcel.EndLocalizeEtcExcel(builder);
  }

  public static void StartLocalizeEtcExcel(FlatBufferBuilder builder) { builder.StartTable(11); }
  public static void AddKey(FlatBufferBuilder builder, uint key) { builder.AddUint(0, key, 0); }
  public static void AddNameKr(FlatBufferBuilder builder, StringOffset nameKrOffset) { builder.AddOffset(1, nameKrOffset.Value, 0); }
  public static void AddDescriptionKr(FlatBufferBuilder builder, StringOffset descriptionKrOffset) { builder.AddOffset(2, descriptionKrOffset.Value, 0); }
  public static void AddNameJp(FlatBufferBuilder builder, StringOffset nameJpOffset) { builder.AddOffset(3, nameJpOffset.Value, 0); }
  public static void AddDescriptionJp(FlatBufferBuilder builder, StringOffset descriptionJpOffset) { builder.AddOffset(4, descriptionJpOffset.Value, 0); }
  public static void AddNameTh(FlatBufferBuilder builder, StringOffset nameThOffset) { builder.AddOffset(5, nameThOffset.Value, 0); }
  public static void AddDescriptionTh(FlatBufferBuilder builder, StringOffset descriptionThOffset) { builder.AddOffset(6, descriptionThOffset.Value, 0); }
  public static void AddNameTw(FlatBufferBuilder builder, StringOffset nameTwOffset) { builder.AddOffset(7, nameTwOffset.Value, 0); }
  public static void AddDescriptionTw(FlatBufferBuilder builder, StringOffset descriptionTwOffset) { builder.AddOffset(8, descriptionTwOffset.Value, 0); }
  public static void AddNameEn(FlatBufferBuilder builder, StringOffset nameEnOffset) { builder.AddOffset(9, nameEnOffset.Value, 0); }
  public static void AddDescriptionEn(FlatBufferBuilder builder, StringOffset descriptionEnOffset) { builder.AddOffset(10, descriptionEnOffset.Value, 0); }
  public static Offset<Plana.FlatData.LocalizeEtcExcel> EndLocalizeEtcExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.LocalizeEtcExcel>(o);
  }
  public LocalizeEtcExcelT UnPack() {
    var _o = new LocalizeEtcExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(LocalizeEtcExcelT _o) {
        byte[] key = TableEncryptionService.CreateKey("LocalizeEtc");
    _o.Key = TableEncryptionService.Convert(this.Key, key);
    _o.NameKr = TableEncryptionService.Convert(this.NameKr, key);
    _o.DescriptionKr = TableEncryptionService.Convert(this.DescriptionKr, key);
    _o.NameJp = TableEncryptionService.Convert(this.NameJp, key);
    _o.DescriptionJp = TableEncryptionService.Convert(this.DescriptionJp, key);
    _o.NameTh = TableEncryptionService.Convert(this.NameTh, key);
    _o.DescriptionTh = TableEncryptionService.Convert(this.DescriptionTh, key);
    _o.NameTw = TableEncryptionService.Convert(this.NameTw, key);
    _o.DescriptionTw = TableEncryptionService.Convert(this.DescriptionTw, key);
    _o.NameEn = TableEncryptionService.Convert(this.NameEn, key);
    _o.DescriptionEn = TableEncryptionService.Convert(this.DescriptionEn, key);
  }
  public static Offset<Plana.FlatData.LocalizeEtcExcel> Pack(FlatBufferBuilder builder, LocalizeEtcExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.LocalizeEtcExcel>);
    var _NameKr = _o.NameKr == null ? default(StringOffset) : builder.CreateString(_o.NameKr);
    var _DescriptionKr = _o.DescriptionKr == null ? default(StringOffset) : builder.CreateString(_o.DescriptionKr);
    var _NameJp = _o.NameJp == null ? default(StringOffset) : builder.CreateString(_o.NameJp);
    var _DescriptionJp = _o.DescriptionJp == null ? default(StringOffset) : builder.CreateString(_o.DescriptionJp);
    var _NameTh = _o.NameTh == null ? default(StringOffset) : builder.CreateString(_o.NameTh);
    var _DescriptionTh = _o.DescriptionTh == null ? default(StringOffset) : builder.CreateString(_o.DescriptionTh);
    var _NameTw = _o.NameTw == null ? default(StringOffset) : builder.CreateString(_o.NameTw);
    var _DescriptionTw = _o.DescriptionTw == null ? default(StringOffset) : builder.CreateString(_o.DescriptionTw);
    var _NameEn = _o.NameEn == null ? default(StringOffset) : builder.CreateString(_o.NameEn);
    var _DescriptionEn = _o.DescriptionEn == null ? default(StringOffset) : builder.CreateString(_o.DescriptionEn);
    return CreateLocalizeEtcExcel(
      builder,
      _o.Key,
      _NameKr,
      _DescriptionKr,
      _NameJp,
      _DescriptionJp,
      _NameTh,
      _DescriptionTh,
      _NameTw,
      _DescriptionTw,
      _NameEn,
      _DescriptionEn);
  }
}

public class LocalizeEtcExcelT
{
  public uint Key { get; set; }
  public string NameKr { get; set; }
  public string DescriptionKr { get; set; }
  public string NameJp { get; set; }
  public string DescriptionJp { get; set; }
  public string NameTh { get; set; }
  public string DescriptionTh { get; set; }
  public string NameTw { get; set; }
  public string DescriptionTw { get; set; }
  public string NameEn { get; set; }
  public string DescriptionEn { get; set; }

  public LocalizeEtcExcelT() {
    this.Key = 0;
    this.NameKr = null;
    this.DescriptionKr = null;
    this.NameJp = null;
    this.DescriptionJp = null;
    this.NameTh = null;
    this.DescriptionTh = null;
    this.NameTw = null;
    this.DescriptionTw = null;
    this.NameEn = null;
    this.DescriptionEn = null;
  }
}


static public class LocalizeEtcExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Key*/, 4 /*uint*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*NameKr*/, false)
      && verifier.VerifyString(tablePos, 8 /*DescriptionKr*/, false)
      && verifier.VerifyString(tablePos, 10 /*NameJp*/, false)
      && verifier.VerifyString(tablePos, 12 /*DescriptionJp*/, false)
      && verifier.VerifyString(tablePos, 14 /*NameTh*/, false)
      && verifier.VerifyString(tablePos, 16 /*DescriptionTh*/, false)
      && verifier.VerifyString(tablePos, 18 /*NameTw*/, false)
      && verifier.VerifyString(tablePos, 20 /*DescriptionTw*/, false)
      && verifier.VerifyString(tablePos, 22 /*NameEn*/, false)
      && verifier.VerifyString(tablePos, 24 /*DescriptionEn*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
