// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum LogicEffectSound : int
{
  None = 0,
  Damage = 1,
  Heal = 2,
  Knockback = 3,
};


}
