// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum LogicEffectCategory : int
{
  None = 0,
  Attack = 1,
  Heal = 2,
  Buff = 3,
  Debuff = 4,
  CrowdControl = 5,
  Boss = 6,
  Dummy = 7,
};


}
