// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum MeetupConditionPrintType : int
{
  None = 0,
  Lock = 1,
  Hide = 2,
};


}
