// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum MessagePopupImagePositionType : int
{
  ImageFirst = 0,
  TextFirst = 1,
};


}
