// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum MessagePopupButtonType : int
{
  Accept = 0,
  Cancel = 1,
  Command = 2,
};


}
