// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum MissionResetType : int
{
  None = 0,
  Daily = 1,
  Weekly = 2,
  Limit = 3,
};


}
