// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum MissionToastDisplayConditionType : int
{
  Always = 0,
  Complete = 1,
  Never = 2,
};


}
