// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum Nation : int
{
  None = 0,
  All = 1,
  JP = 2,
  GL = 3,
  KR = 4,
};


}
