// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum NexonBillingState : int
{
  ValiDateWait = 0,
  ValiDateFail = 1,
  ValiDateSuccess = 2,
  Finish = 3,
};


}
