// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum NotificationEventReddot : int
{
  StagePointReward = 0,
  MissionComplete = 1,
  MiniGameMissionComplete = 2,
  WorldRaidReward = 3,
  ConquestCalculateReward = 4,
  DiceRaceLapReward = 5,
};


}
