// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum NoticeType : int
{
  None = 0,
  Notice = 1,
  Event = 2,
};


}
