// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum OpenCondition : int
{
  Hide = 0,
  Lock = 1,
  Open = 2,
};


}
