// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum PositioningType : int
{
  CloseToObstacle = 0,
  CloseToTarget = 1,
};


}
