// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum PotentialStatBonusRateType : int
{
  None = 0,
  MaxHP = 1,
  AttackPower = 2,
  HealPower = 3,
};


}
