// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ProductTagType : int
{
  Monthly = 0,
  Weekly = 1,
  Biweekly = 2,
};


}
