// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ProductCategory : int
{
  None = 0,
  Gem = 1,
  Monthly = 2,
  Package = 3,
  GachaDirect_DontUseGlobal = 4,
  TimeLimit = 5,
};


}
