// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum ProjectileAction : int
{
  None = 0,
  Damage = 1,
  Heal = 2,
};


}
