// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum PurchaseStatusCode : int
{
  None = 0,
  Start = 1,
  PublishSuccess = 2,
  End = 3,
  Error = 4,
  DuplicateOrder = 5,
  Refund = 6,
};


}
