// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum PurchaseServerTag : int
{
  Audit = 0,
  PreAudit = 1,
  Production = 2,
  Hotfix = 3,
  Standby2 = 4,
  Standby1 = 5,
  Major = 6,
  Minor = 7,
  Temp = 8,
  Test = 9,
  TestIn = 10,
};


}
