// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum PurchaseCountResetType : int
{
  None = 0,
  Day = 1,
  Week = 2,
  Month = 3,
};


}
