// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum RaidStatus : int
{
  None = 0,
  Playing = 1,
  Clear = 2,
  Close = 3,
};


}
