// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum Rarity : int
{
  N = 0,
  R = 1,
  SR = 2,
  SSR = 3,
};


}
