// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum RecipeType : int
{
  None = 0,
  Craft = 1,
  SkillLevelUp = 2,
  CharacterTranscendence = 3,
  EquipmentTierUp = 4,
  CafeRankUp = 5,
  SelectionItem = 6,
  WeaponTranscendence = 7,
  SelectRecruit = 8,
  CharacterPotential = 9,
};


}
