// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ResetContentType : int
{
  None = 0,
  HardStagePlay = 1,
  StarategyMapHeal = 2,
  ShopRefresh = 3,
  ArenaDefenseVictoryReward = 4,
  WeeklyMasterCoin = 5,
  WorldRaidGemEnterCount = 6,
  ConquestDailyErosionCheck = 7,
  MiniEventToken = 8,
};


}
