// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioBGScroll : int
{
  None = 0,
  Vertical = 1,
  Horizontal = 2,
};


}
