// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioBGType : int
{
  None = 0,
  Image = 1,
  BlurRT = 2,
  Spine = 3,
  Hide = 4,
};


}
