// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioCharacterBehaviors : int
{
  None = 0,
  Appear = 1,
  Disappear = 2,
  AppearToLeft = 3,
  ApperToRight = 4,
  DisappearToLeft = 5,
  DisappearToRight = 6,
  MoveToTarget = 7,
};


}
