// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioModeSubTypes : int
{
  None = 0,
  Club = 1,
  TSS = 2,
};


}
