// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioZoomType : int
{
  Instant = 0,
  Slide = 1,
};


}
