// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ScenarioEffectDepth : int
{
  None = 0,
  AboveBg = 1,
  AboveCharacter = 2,
  AboveAll = 3,
};


}
