// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum School : int
{
  None = 0,
  Hyakkiyako = 1,
  RedWinter = 2,
  Trinity = 3,
  Gehenna = 4,
  Abydos = 5,
  Millennium = 6,
  Arius = 7,
  Shanhaijing = 8,
  Valkyrie = 9,
  WildHunt = 10,
  SRT = 11,
  SCHALE = 12,
  ETC = 13,
  Tokiwadai = 14,
  Sakugawa = 15,
};


}
