// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum SchoolDungeonType : int
{
  SchoolA = 0,
  SchoolB = 1,
  SchoolC = 2,
  None = 3,
};


}
