// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ShopFreeRecruitType : int
{
  None = 0,
  Accumulation = 1,
  Reset = 2,
};


}
