// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ShortcutContentType : int
{
  None = 0,
  CampaignStage = 1,
  EventStage = 2,
  Blood = 3,
  WeekDungeon = 4,
  Arena = 5,
  Raid = 6,
  Shop = 7,
  ItemInventory = 8,
  Craft = 9,
  SchoolDungeon = 10,
  Academy = 11,
  Mission = 12,
  MultiFloorRaid = 13,
};


}
