// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum ShowSkillCutIn : int
{
  None = 0,
  Once = 1,
  Always = 2,
};


}
