// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum SkillPriorityCheckCondition : int
{
  None = 0,
  HPRateUnder = 1,
  DebuffCountOver = 2,
  BuffCountOver = 3,
  CrowdControlOver = 4,
};


}
