// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum SoundType : int
{
  UI = 0,
  BGM = 1,
  FX = 2,
};


}
