// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum StageDifficulty : int
{
  None = 0,
  Normal = 1,
  Hard = 2,
  VeryHard = 3,
  VeryHard_Ex = 4,
};


}
