// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum StarGoalType : int
{
  None = 0,
  AllAlive = 1,
  Clear = 2,
  GetBoxes = 3,
  ClearTimeInSec = 4,
};


}
