// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum StatTransType : int
{
  SpecialTransStat = 0,
  TSATransStat = 1,
};


}
