// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum StatTransType : int
{
  SpecialTransStat = 0,
  TSATransStat = 1,
};


}
