// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum StoryCondition : int
{
  Open = 0,
  Locked = 1,
  ComingSoon = 2,
  Hide = 3,
};


}
