// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct TacticSimulatorSettingExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static TacticSimulatorSettingExcel GetRootAsTacticSimulatorSettingExcel(ByteBuffer _bb) { return GetRootAsTacticSimulatorSettingExcel(_bb, new TacticSimulatorSettingExcel()); }
  public static TacticSimulatorSettingExcel GetRootAsTacticSimulatorSettingExcel(ByteBuffer _bb, TacticSimulatorSettingExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TacticSimulatorSettingExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long GroundId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long FixedEchelonId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Plana.FlatData.TacticSimulatorSettingExcel> CreateTacticSimulatorSettingExcel(FlatBufferBuilder builder,
      long GroundId = 0,
      long FixedEchelonId = 0) {
    builder.StartTable(2);
    TacticSimulatorSettingExcel.AddFixedEchelonId(builder, FixedEchelonId);
    TacticSimulatorSettingExcel.AddGroundId(builder, GroundId);
    return TacticSimulatorSettingExcel.EndTacticSimulatorSettingExcel(builder);
  }

  public static void StartTacticSimulatorSettingExcel(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddGroundId(FlatBufferBuilder builder, long groundId) { builder.AddLong(0, groundId, 0); }
  public static void AddFixedEchelonId(FlatBufferBuilder builder, long fixedEchelonId) { builder.AddLong(1, fixedEchelonId, 0); }
  public static Offset<Plana.FlatData.TacticSimulatorSettingExcel> EndTacticSimulatorSettingExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.TacticSimulatorSettingExcel>(o);
  }
  public TacticSimulatorSettingExcelT UnPack() {
    var _o = new TacticSimulatorSettingExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(TacticSimulatorSettingExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("TacticSimulatorSetting");
    _o.GroundId = TableEncryptionService.Convert(this.GroundId, key);
    _o.FixedEchelonId = TableEncryptionService.Convert(this.FixedEchelonId, key);
  }
  public static Offset<Plana.FlatData.TacticSimulatorSettingExcel> Pack(FlatBufferBuilder builder, TacticSimulatorSettingExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.TacticSimulatorSettingExcel>);
    return CreateTacticSimulatorSettingExcel(
      builder,
      _o.GroundId,
      _o.FixedEchelonId);
  }
}

public class TacticSimulatorSettingExcelT
{
  public long GroundId { get; set; }
  public long FixedEchelonId { get; set; }

  public TacticSimulatorSettingExcelT() {
    this.GroundId = 0;
    this.FixedEchelonId = 0;
  }
}


static public class TacticSimulatorSettingExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*GroundId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*FixedEchelonId*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
