// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TacticSpeed : int
{
  None = 0,
  Slow = 1,
  Normal = 2,
  Fast = 3,
};


}
