// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TacticRole : int
{
  None = 0,
  DamageDealer = 1,
  Tanker = 2,
  Supporter = 3,
  Healer = 4,
  Vehicle = 5,
};


}
