// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TBGItemEffectType : int
{
  None = 0,
  PermanentContinuity = 1,
  TemporaryContinuation = 2,
  Immediately = 3,
};


}
