// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum TBGOptionSuccessType : int
{
  None = 0,
  TBGItemAcquire = 1,
  ItemAcquire = 2,
  TBGDiceAcquire = 3,
  Portal = 4,
};


}
