// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TBGThemaType : int
{
  None = 0,
  Normal = 1,
  Hidden = 2,
};


}
