// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TBGTileType : int
{
  None = 0,
  Start = 1,
  Movable = 2,
  UnMovable = 3,
};


}
