// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum TBGVoiceCondition : int
{
  None = 0,
  DiceResultSuccess = 1,
  DiceResultFailBattle = 2,
  DiceResultFailRandom = 3,
  EnemyDie = 4,
  TreasureBoxNormal = 5,
  TreasureBoxSpecial = 6,
  FacilityResult = 7,
};


}
