// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum Tier : int
{
  T1 = 0,
  T2 = 1,
  T3 = 2,
  T4 = 3,
};


}
