// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum TimeAttackDungeonRewardType : int
{
  Fixed = 0,
  TimeWeight = 1,
};


}
