// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum ToastType : int
{
  None = 0,
  Tactic_Left = 1,
  Tactic_Right = 2,
  Social_Center = 3,
  Social_Mission = 4,
  Social_Right = 5,
  Notice_Center = 6,
};


}
