// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

public enum UnderCoverItemCategory : int
{
  Consumable = 0,
  Interaction = 1,
  Skill = 2,
  Collection = 3,
};


}
