// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct Video_GlobalExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Video_GlobalExcel GetRootAsVideo_GlobalExcel(ByteBuffer _bb) { return GetRootAsVideo_GlobalExcel(_bb, new Video_GlobalExcel()); }
  public static Video_GlobalExcel GetRootAsVideo_GlobalExcel(ByteBuffer _bb, Video_GlobalExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Video_GlobalExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long VideoId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string VideoPathKr { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoPathKrBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetVideoPathKrBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetVideoPathKrArray() { return __p.__vector_as_array<byte>(6); }
  public string VideoTeenPathKr { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoTeenPathKrBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetVideoTeenPathKrBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetVideoTeenPathKrArray() { return __p.__vector_as_array<byte>(8); }
  public string VideoPathTh { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoPathThBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetVideoPathThBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetVideoPathThArray() { return __p.__vector_as_array<byte>(10); }
  public string VideoTeenPathTh { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoTeenPathThBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetVideoTeenPathThBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetVideoTeenPathThArray() { return __p.__vector_as_array<byte>(12); }
  public string VideoPathTw { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoPathTwBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetVideoPathTwBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetVideoPathTwArray() { return __p.__vector_as_array<byte>(14); }
  public string VideoTeenPathTw { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoTeenPathTwBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetVideoTeenPathTwBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetVideoTeenPathTwArray() { return __p.__vector_as_array<byte>(16); }
  public string VideoPathEn { get { int o = __p.__offset(18); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoPathEnBytes() { return __p.__vector_as_span<byte>(18, 1); }
#else
  public ArraySegment<byte>? GetVideoPathEnBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public byte[] GetVideoPathEnArray() { return __p.__vector_as_array<byte>(18); }
  public string VideoTeenPathEn { get { int o = __p.__offset(20); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetVideoTeenPathEnBytes() { return __p.__vector_as_span<byte>(20, 1); }
#else
  public ArraySegment<byte>? GetVideoTeenPathEnBytes() { return __p.__vector_as_arraysegment(20); }
#endif
  public byte[] GetVideoTeenPathEnArray() { return __p.__vector_as_array<byte>(20); }

  public static Offset<Plana.FlatData.Video_GlobalExcel> CreateVideo_GlobalExcel(FlatBufferBuilder builder,
      long VideoId = 0,
      StringOffset VideoPathKrOffset = default(StringOffset),
      StringOffset VideoTeenPathKrOffset = default(StringOffset),
      StringOffset VideoPathThOffset = default(StringOffset),
      StringOffset VideoTeenPathThOffset = default(StringOffset),
      StringOffset VideoPathTwOffset = default(StringOffset),
      StringOffset VideoTeenPathTwOffset = default(StringOffset),
      StringOffset VideoPathEnOffset = default(StringOffset),
      StringOffset VideoTeenPathEnOffset = default(StringOffset)) {
    builder.StartTable(9);
    Video_GlobalExcel.AddVideoId(builder, VideoId);
    Video_GlobalExcel.AddVideoTeenPathEn(builder, VideoTeenPathEnOffset);
    Video_GlobalExcel.AddVideoPathEn(builder, VideoPathEnOffset);
    Video_GlobalExcel.AddVideoTeenPathTw(builder, VideoTeenPathTwOffset);
    Video_GlobalExcel.AddVideoPathTw(builder, VideoPathTwOffset);
    Video_GlobalExcel.AddVideoTeenPathTh(builder, VideoTeenPathThOffset);
    Video_GlobalExcel.AddVideoPathTh(builder, VideoPathThOffset);
    Video_GlobalExcel.AddVideoTeenPathKr(builder, VideoTeenPathKrOffset);
    Video_GlobalExcel.AddVideoPathKr(builder, VideoPathKrOffset);
    return Video_GlobalExcel.EndVideo_GlobalExcel(builder);
  }

  public static void StartVideo_GlobalExcel(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddVideoId(FlatBufferBuilder builder, long videoId) { builder.AddLong(0, videoId, 0); }
  public static void AddVideoPathKr(FlatBufferBuilder builder, StringOffset videoPathKrOffset) { builder.AddOffset(1, videoPathKrOffset.Value, 0); }
  public static void AddVideoTeenPathKr(FlatBufferBuilder builder, StringOffset videoTeenPathKrOffset) { builder.AddOffset(2, videoTeenPathKrOffset.Value, 0); }
  public static void AddVideoPathTh(FlatBufferBuilder builder, StringOffset videoPathThOffset) { builder.AddOffset(3, videoPathThOffset.Value, 0); }
  public static void AddVideoTeenPathTh(FlatBufferBuilder builder, StringOffset videoTeenPathThOffset) { builder.AddOffset(4, videoTeenPathThOffset.Value, 0); }
  public static void AddVideoPathTw(FlatBufferBuilder builder, StringOffset videoPathTwOffset) { builder.AddOffset(5, videoPathTwOffset.Value, 0); }
  public static void AddVideoTeenPathTw(FlatBufferBuilder builder, StringOffset videoTeenPathTwOffset) { builder.AddOffset(6, videoTeenPathTwOffset.Value, 0); }
  public static void AddVideoPathEn(FlatBufferBuilder builder, StringOffset videoPathEnOffset) { builder.AddOffset(7, videoPathEnOffset.Value, 0); }
  public static void AddVideoTeenPathEn(FlatBufferBuilder builder, StringOffset videoTeenPathEnOffset) { builder.AddOffset(8, videoTeenPathEnOffset.Value, 0); }
  public static Offset<Plana.FlatData.Video_GlobalExcel> EndVideo_GlobalExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.Video_GlobalExcel>(o);
  }
  public Video_GlobalExcelT UnPack() {
    var _o = new Video_GlobalExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(Video_GlobalExcelT _o) {
        byte[] key = TableEncryptionService.CreateKey("Video_Global");
    _o.VideoId = TableEncryptionService.Convert(this.VideoId, key);
    _o.VideoPathKr = TableEncryptionService.Convert(this.VideoPathKr, key);
    _o.VideoTeenPathKr = TableEncryptionService.Convert(this.VideoTeenPathKr, key);
    _o.VideoPathTh = TableEncryptionService.Convert(this.VideoPathTh, key);
    _o.VideoTeenPathTh = TableEncryptionService.Convert(this.VideoTeenPathTh, key);
    _o.VideoPathTw = TableEncryptionService.Convert(this.VideoPathTw, key);
    _o.VideoTeenPathTw = TableEncryptionService.Convert(this.VideoTeenPathTw, key);
    _o.VideoPathEn = TableEncryptionService.Convert(this.VideoPathEn, key);
    _o.VideoTeenPathEn = TableEncryptionService.Convert(this.VideoTeenPathEn, key);
  }
  public static Offset<Plana.FlatData.Video_GlobalExcel> Pack(FlatBufferBuilder builder, Video_GlobalExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.Video_GlobalExcel>);
    var _VideoPathKr = _o.VideoPathKr == null ? default(StringOffset) : builder.CreateString(_o.VideoPathKr);
    var _VideoTeenPathKr = _o.VideoTeenPathKr == null ? default(StringOffset) : builder.CreateString(_o.VideoTeenPathKr);
    var _VideoPathTh = _o.VideoPathTh == null ? default(StringOffset) : builder.CreateString(_o.VideoPathTh);
    var _VideoTeenPathTh = _o.VideoTeenPathTh == null ? default(StringOffset) : builder.CreateString(_o.VideoTeenPathTh);
    var _VideoPathTw = _o.VideoPathTw == null ? default(StringOffset) : builder.CreateString(_o.VideoPathTw);
    var _VideoTeenPathTw = _o.VideoTeenPathTw == null ? default(StringOffset) : builder.CreateString(_o.VideoTeenPathTw);
    var _VideoPathEn = _o.VideoPathEn == null ? default(StringOffset) : builder.CreateString(_o.VideoPathEn);
    var _VideoTeenPathEn = _o.VideoTeenPathEn == null ? default(StringOffset) : builder.CreateString(_o.VideoTeenPathEn);
    return CreateVideo_GlobalExcel(
      builder,
      _o.VideoId,
      _VideoPathKr,
      _VideoTeenPathKr,
      _VideoPathTh,
      _VideoTeenPathTh,
      _VideoPathTw,
      _VideoTeenPathTw,
      _VideoPathEn,
      _VideoTeenPathEn);
  }
}

public class Video_GlobalExcelT
{
  public long VideoId { get; set; }
  public string VideoPathKr { get; set; }
  public string VideoTeenPathKr { get; set; }
  public string VideoPathTh { get; set; }
  public string VideoTeenPathTh { get; set; }
  public string VideoPathTw { get; set; }
  public string VideoTeenPathTw { get; set; }
  public string VideoPathEn { get; set; }
  public string VideoTeenPathEn { get; set; }

  public Video_GlobalExcelT() {
    this.VideoId = 0;
    this.VideoPathKr = null;
    this.VideoTeenPathKr = null;
    this.VideoPathTh = null;
    this.VideoTeenPathTh = null;
    this.VideoPathTw = null;
    this.VideoTeenPathTw = null;
    this.VideoPathEn = null;
    this.VideoTeenPathEn = null;
  }
}


static public class Video_GlobalExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*VideoId*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*VideoPathKr*/, false)
      && verifier.VerifyString(tablePos, 8 /*VideoTeenPathKr*/, false)
      && verifier.VerifyString(tablePos, 10 /*VideoPathTh*/, false)
      && verifier.VerifyString(tablePos, 12 /*VideoTeenPathTh*/, false)
      && verifier.VerifyString(tablePos, 14 /*VideoPathTw*/, false)
      && verifier.VerifyString(tablePos, 16 /*VideoTeenPathTw*/, false)
      && verifier.VerifyString(tablePos, 18 /*VideoPathEn*/, false)
      && verifier.VerifyString(tablePos, 20 /*VideoTeenPathEn*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
