// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct VoiceRoomExceptionExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static VoiceRoomExceptionExcel GetRootAsVoiceRoomExceptionExcel(ByteBuffer _bb) { return GetRootAsVoiceRoomExceptionExcel(_bb, new VoiceRoomExceptionExcel()); }
  public static VoiceRoomExceptionExcel GetRootAsVoiceRoomExceptionExcel(ByteBuffer _bb, VoiceRoomExceptionExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VoiceRoomExceptionExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long CostumeUniqueId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Plana.FlatData.CVPrintType LinkedCharacterVoicePrintType { get { int o = __p.__offset(6); return o != 0 ? (Plana.FlatData.CVPrintType)__p.bb.GetInt(o + __p.bb_pos) : Plana.FlatData.CVPrintType.CharacterOverwrite; } }
  public long LinkedCostumeUniqueId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Plana.FlatData.VoiceRoomExceptionExcel> CreateVoiceRoomExceptionExcel(FlatBufferBuilder builder,
      long CostumeUniqueId = 0,
      Plana.FlatData.CVPrintType LinkedCharacterVoicePrintType = Plana.FlatData.CVPrintType.CharacterOverwrite,
      long LinkedCostumeUniqueId = 0) {
    builder.StartTable(3);
    VoiceRoomExceptionExcel.AddLinkedCostumeUniqueId(builder, LinkedCostumeUniqueId);
    VoiceRoomExceptionExcel.AddCostumeUniqueId(builder, CostumeUniqueId);
    VoiceRoomExceptionExcel.AddLinkedCharacterVoicePrintType(builder, LinkedCharacterVoicePrintType);
    return VoiceRoomExceptionExcel.EndVoiceRoomExceptionExcel(builder);
  }

  public static void StartVoiceRoomExceptionExcel(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddCostumeUniqueId(FlatBufferBuilder builder, long costumeUniqueId) { builder.AddLong(0, costumeUniqueId, 0); }
  public static void AddLinkedCharacterVoicePrintType(FlatBufferBuilder builder, Plana.FlatData.CVPrintType linkedCharacterVoicePrintType) { builder.AddInt(1, (int)linkedCharacterVoicePrintType, 0); }
  public static void AddLinkedCostumeUniqueId(FlatBufferBuilder builder, long linkedCostumeUniqueId) { builder.AddLong(2, linkedCostumeUniqueId, 0); }
  public static Offset<Plana.FlatData.VoiceRoomExceptionExcel> EndVoiceRoomExceptionExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.VoiceRoomExceptionExcel>(o);
  }
  public VoiceRoomExceptionExcelT UnPack() {
    var _o = new VoiceRoomExceptionExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(VoiceRoomExceptionExcelT _o) {
		byte[] key = TableEncryptionService.CreateKey("VoiceRoomException");
    _o.CostumeUniqueId = TableEncryptionService.Convert(this.CostumeUniqueId, key);
    _o.LinkedCharacterVoicePrintType = TableEncryptionService.Convert(this.LinkedCharacterVoicePrintType, key);
    _o.LinkedCostumeUniqueId = TableEncryptionService.Convert(this.LinkedCostumeUniqueId, key);
  }
  public static Offset<Plana.FlatData.VoiceRoomExceptionExcel> Pack(FlatBufferBuilder builder, VoiceRoomExceptionExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.VoiceRoomExceptionExcel>);
    return CreateVoiceRoomExceptionExcel(
      builder,
      _o.CostumeUniqueId,
      _o.LinkedCharacterVoicePrintType,
      _o.LinkedCostumeUniqueId);
  }
}

public class VoiceRoomExceptionExcelT
{
  public long CostumeUniqueId { get; set; }
  public Plana.FlatData.CVPrintType LinkedCharacterVoicePrintType { get; set; }
  public long LinkedCostumeUniqueId { get; set; }

  public VoiceRoomExceptionExcelT() {
    this.CostumeUniqueId = 0;
    this.LinkedCharacterVoicePrintType = Plana.FlatData.CVPrintType.CharacterOverwrite;
    this.LinkedCostumeUniqueId = 0;
  }
}


static public class VoiceRoomExceptionExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*CostumeUniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*LinkedCharacterVoicePrintType*/, 4 /*Plana.FlatData.CVPrintType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*LinkedCostumeUniqueId*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
