// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum WebAPIErrorLevel : int
{
  None = 0,
  Warning = 1,
  Error = 2,
};


}
