// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

using global::System;
using global::System.Collections.Generic;
using global::Plana.Crypto;
using global::Google.FlatBuffers;

public struct WeekDungeonExcel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static WeekDungeonExcel GetRootAsWeekDungeonExcel(ByteBuffer _bb) { return GetRootAsWeekDungeonExcel(_bb, new WeekDungeonExcel()); }
  public static WeekDungeonExcel GetRootAsWeekDungeonExcel(ByteBuffer _bb, WeekDungeonExcel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public WeekDungeonExcel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long StageId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Plana.FlatData.WeekDungeonType WeekDungeonType_ { get { int o = __p.__offset(6); return o != 0 ? (Plana.FlatData.WeekDungeonType)__p.bb.GetInt(o + __p.bb_pos) : Plana.FlatData.WeekDungeonType.None; } }
  public int Difficulty { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public long BattleDuration { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PrevStageId { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public Plana.FlatData.ParcelType StageEnterCostType(int j) { int o = __p.__offset(14); return o != 0 ? (Plana.FlatData.ParcelType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Plana.FlatData.ParcelType)0; }
  public int StageEnterCostTypeLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Plana.FlatData.ParcelType> GetStageEnterCostTypeBytes() { return __p.__vector_as_span<Plana.FlatData.ParcelType>(14, 4); }
#else
  public ArraySegment<byte>? GetStageEnterCostTypeBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public Plana.FlatData.ParcelType[] GetStageEnterCostTypeArray() { int o = __p.__offset(14); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Plana.FlatData.ParcelType[] a = new Plana.FlatData.ParcelType[l]; for (int i = 0; i < l; i++) { a[i] = (Plana.FlatData.ParcelType)__p.bb.GetInt(p + i * 4); } return a; }
  public long StageEnterCostId(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int StageEnterCostIdLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetStageEnterCostIdBytes() { return __p.__vector_as_span<long>(16, 8); }
#else
  public ArraySegment<byte>? GetStageEnterCostIdBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public long[] GetStageEnterCostIdArray() { return __p.__vector_as_array<long>(16); }
  public int StageEnterCostAmount(int j) { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int StageEnterCostAmountLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetStageEnterCostAmountBytes() { return __p.__vector_as_span<int>(18, 4); }
#else
  public ArraySegment<byte>? GetStageEnterCostAmountBytes() { return __p.__vector_as_arraysegment(18); }
#endif
  public int[] GetStageEnterCostAmountArray() { return __p.__vector_as_array<int>(18); }
  public int GroundId { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public Plana.FlatData.StarGoalType StarGoal(int j) { int o = __p.__offset(22); return o != 0 ? (Plana.FlatData.StarGoalType)__p.bb.GetInt(__p.__vector(o) + j * 4) : (Plana.FlatData.StarGoalType)0; }
  public int StarGoalLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<Plana.FlatData.StarGoalType> GetStarGoalBytes() { return __p.__vector_as_span<Plana.FlatData.StarGoalType>(22, 4); }
#else
  public ArraySegment<byte>? GetStarGoalBytes() { return __p.__vector_as_arraysegment(22); }
#endif
  public Plana.FlatData.StarGoalType[] GetStarGoalArray() { int o = __p.__offset(22); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); Plana.FlatData.StarGoalType[] a = new Plana.FlatData.StarGoalType[l]; for (int i = 0; i < l; i++) { a[i] = (Plana.FlatData.StarGoalType)__p.bb.GetInt(p + i * 4); } return a; }
  public int StarGoalAmount(int j) { int o = __p.__offset(24); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int StarGoalAmountLength { get { int o = __p.__offset(24); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetStarGoalAmountBytes() { return __p.__vector_as_span<int>(24, 4); }
#else
  public ArraySegment<byte>? GetStarGoalAmountBytes() { return __p.__vector_as_arraysegment(24); }
#endif
  public int[] GetStarGoalAmountArray() { return __p.__vector_as_array<int>(24); }
  public Plana.FlatData.StageTopography StageTopography_ { get { int o = __p.__offset(26); return o != 0 ? (Plana.FlatData.StageTopography)__p.bb.GetInt(o + __p.bb_pos) : Plana.FlatData.StageTopography.Street; } }
  public long RecommandLevel { get { int o = __p.__offset(28); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long StageRewardId { get { int o = __p.__offset(30); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long PlayTimeLimitInSeconds { get { int o = __p.__offset(32); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long BattleRewardExp { get { int o = __p.__offset(34); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long BattleRewardPlayerExp { get { int o = __p.__offset(36); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public long GroupBuffID(int j) { int o = __p.__offset(38); return o != 0 ? __p.bb.GetLong(__p.__vector(o) + j * 8) : (long)0; }
  public int GroupBuffIDLength { get { int o = __p.__offset(38); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<long> GetGroupBuffIDBytes() { return __p.__vector_as_span<long>(38, 8); }
#else
  public ArraySegment<byte>? GetGroupBuffIDBytes() { return __p.__vector_as_arraysegment(38); }
#endif
  public long[] GetGroupBuffIDArray() { return __p.__vector_as_array<long>(38); }
  public Plana.FlatData.EchelonExtensionType EchelonExtensionType_ { get { int o = __p.__offset(40); return o != 0 ? (Plana.FlatData.EchelonExtensionType)__p.bb.GetInt(o + __p.bb_pos) : Plana.FlatData.EchelonExtensionType.Base; } }

  public static Offset<Plana.FlatData.WeekDungeonExcel> CreateWeekDungeonExcel(FlatBufferBuilder builder,
      long StageId = 0,
      Plana.FlatData.WeekDungeonType WeekDungeonType_ = Plana.FlatData.WeekDungeonType.None,
      int Difficulty = 0,
      long BattleDuration = 0,
      long PrevStageId = 0,
      VectorOffset StageEnterCostTypeOffset = default(VectorOffset),
      VectorOffset StageEnterCostIdOffset = default(VectorOffset),
      VectorOffset StageEnterCostAmountOffset = default(VectorOffset),
      int GroundId = 0,
      VectorOffset StarGoalOffset = default(VectorOffset),
      VectorOffset StarGoalAmountOffset = default(VectorOffset),
      Plana.FlatData.StageTopography StageTopography_ = Plana.FlatData.StageTopography.Street,
      long RecommandLevel = 0,
      long StageRewardId = 0,
      long PlayTimeLimitInSeconds = 0,
      long BattleRewardExp = 0,
      long BattleRewardPlayerExp = 0,
      VectorOffset GroupBuffIDOffset = default(VectorOffset),
      Plana.FlatData.EchelonExtensionType EchelonExtensionType_ = Plana.FlatData.EchelonExtensionType.Base) {
    builder.StartTable(19);
    WeekDungeonExcel.AddBattleRewardPlayerExp(builder, BattleRewardPlayerExp);
    WeekDungeonExcel.AddBattleRewardExp(builder, BattleRewardExp);
    WeekDungeonExcel.AddPlayTimeLimitInSeconds(builder, PlayTimeLimitInSeconds);
    WeekDungeonExcel.AddStageRewardId(builder, StageRewardId);
    WeekDungeonExcel.AddRecommandLevel(builder, RecommandLevel);
    WeekDungeonExcel.AddPrevStageId(builder, PrevStageId);
    WeekDungeonExcel.AddBattleDuration(builder, BattleDuration);
    WeekDungeonExcel.AddStageId(builder, StageId);
    WeekDungeonExcel.AddEchelonExtensionType_(builder, EchelonExtensionType_);
    WeekDungeonExcel.AddGroupBuffID(builder, GroupBuffIDOffset);
    WeekDungeonExcel.AddStageTopography_(builder, StageTopography_);
    WeekDungeonExcel.AddStarGoalAmount(builder, StarGoalAmountOffset);
    WeekDungeonExcel.AddStarGoal(builder, StarGoalOffset);
    WeekDungeonExcel.AddGroundId(builder, GroundId);
    WeekDungeonExcel.AddStageEnterCostAmount(builder, StageEnterCostAmountOffset);
    WeekDungeonExcel.AddStageEnterCostId(builder, StageEnterCostIdOffset);
    WeekDungeonExcel.AddStageEnterCostType(builder, StageEnterCostTypeOffset);
    WeekDungeonExcel.AddDifficulty(builder, Difficulty);
    WeekDungeonExcel.AddWeekDungeonType_(builder, WeekDungeonType_);
    return WeekDungeonExcel.EndWeekDungeonExcel(builder);
  }

  public static void StartWeekDungeonExcel(FlatBufferBuilder builder) { builder.StartTable(19); }
  public static void AddStageId(FlatBufferBuilder builder, long stageId) { builder.AddLong(0, stageId, 0); }
  public static void AddWeekDungeonType_(FlatBufferBuilder builder, Plana.FlatData.WeekDungeonType weekDungeonType_) { builder.AddInt(1, (int)weekDungeonType_, 0); }
  public static void AddDifficulty(FlatBufferBuilder builder, int difficulty) { builder.AddInt(2, difficulty, 0); }
  public static void AddBattleDuration(FlatBufferBuilder builder, long battleDuration) { builder.AddLong(3, battleDuration, 0); }
  public static void AddPrevStageId(FlatBufferBuilder builder, long prevStageId) { builder.AddLong(4, prevStageId, 0); }
  public static void AddStageEnterCostType(FlatBufferBuilder builder, VectorOffset stageEnterCostTypeOffset) { builder.AddOffset(5, stageEnterCostTypeOffset.Value, 0); }
  public static VectorOffset CreateStageEnterCostTypeVector(FlatBufferBuilder builder, Plana.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostTypeVectorBlock(FlatBufferBuilder builder, Plana.FlatData.ParcelType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostTypeVectorBlock(FlatBufferBuilder builder, ArraySegment<Plana.FlatData.ParcelType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostTypeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Plana.FlatData.ParcelType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStageEnterCostTypeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStageEnterCostId(FlatBufferBuilder builder, VectorOffset stageEnterCostIdOffset) { builder.AddOffset(6, stageEnterCostIdOffset.Value, 0); }
  public static VectorOffset CreateStageEnterCostIdVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostIdVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostIdVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostIdVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStageEnterCostIdVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddStageEnterCostAmount(FlatBufferBuilder builder, VectorOffset stageEnterCostAmountOffset) { builder.AddOffset(7, stageEnterCostAmountOffset.Value, 0); }
  public static VectorOffset CreateStageEnterCostAmountVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostAmountVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStageEnterCostAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStageEnterCostAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddGroundId(FlatBufferBuilder builder, int groundId) { builder.AddInt(8, groundId, 0); }
  public static void AddStarGoal(FlatBufferBuilder builder, VectorOffset starGoalOffset) { builder.AddOffset(9, starGoalOffset.Value, 0); }
  public static VectorOffset CreateStarGoalVector(FlatBufferBuilder builder, Plana.FlatData.StarGoalType[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalVectorBlock(FlatBufferBuilder builder, Plana.FlatData.StarGoalType[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalVectorBlock(FlatBufferBuilder builder, ArraySegment<Plana.FlatData.StarGoalType> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Plana.FlatData.StarGoalType>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStarGoalVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStarGoalAmount(FlatBufferBuilder builder, VectorOffset starGoalAmountOffset) { builder.AddOffset(10, starGoalAmountOffset.Value, 0); }
  public static VectorOffset CreateStarGoalAmountVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalAmountVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalAmountVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStarGoalAmountVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStarGoalAmountVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddStageTopography_(FlatBufferBuilder builder, Plana.FlatData.StageTopography stageTopography_) { builder.AddInt(11, (int)stageTopography_, 0); }
  public static void AddRecommandLevel(FlatBufferBuilder builder, long recommandLevel) { builder.AddLong(12, recommandLevel, 0); }
  public static void AddStageRewardId(FlatBufferBuilder builder, long stageRewardId) { builder.AddLong(13, stageRewardId, 0); }
  public static void AddPlayTimeLimitInSeconds(FlatBufferBuilder builder, long playTimeLimitInSeconds) { builder.AddLong(14, playTimeLimitInSeconds, 0); }
  public static void AddBattleRewardExp(FlatBufferBuilder builder, long battleRewardExp) { builder.AddLong(15, battleRewardExp, 0); }
  public static void AddBattleRewardPlayerExp(FlatBufferBuilder builder, long battleRewardPlayerExp) { builder.AddLong(16, battleRewardPlayerExp, 0); }
  public static void AddGroupBuffID(FlatBufferBuilder builder, VectorOffset groupBuffIDOffset) { builder.AddOffset(17, groupBuffIDOffset.Value, 0); }
  public static VectorOffset CreateGroupBuffIDVector(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); for (int i = data.Length - 1; i >= 0; i--) builder.AddLong(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateGroupBuffIDVectorBlock(FlatBufferBuilder builder, long[] data) { builder.StartVector(8, data.Length, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGroupBuffIDVectorBlock(FlatBufferBuilder builder, ArraySegment<long> data) { builder.StartVector(8, data.Count, 8); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateGroupBuffIDVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<long>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartGroupBuffIDVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(8, numElems, 8); }
  public static void AddEchelonExtensionType_(FlatBufferBuilder builder, Plana.FlatData.EchelonExtensionType echelonExtensionType_) { builder.AddInt(18, (int)echelonExtensionType_, 0); }
  public static Offset<Plana.FlatData.WeekDungeonExcel> EndWeekDungeonExcel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Plana.FlatData.WeekDungeonExcel>(o);
  }
  public WeekDungeonExcelT UnPack() {
    var _o = new WeekDungeonExcelT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(WeekDungeonExcelT _o) {
        byte[] key = TableEncryptionService.CreateKey("WeekDungeon");
    _o.StageId = TableEncryptionService.Convert(this.StageId, key);
    _o.WeekDungeonType_ = TableEncryptionService.Convert(this.WeekDungeonType_, key);
    _o.Difficulty = TableEncryptionService.Convert(this.Difficulty, key);
    _o.BattleDuration = TableEncryptionService.Convert(this.BattleDuration, key);
    _o.PrevStageId = TableEncryptionService.Convert(this.PrevStageId, key);
    _o.StageEnterCostType = new List<Plana.FlatData.ParcelType>();
    for (var _j = 0; _j < this.StageEnterCostTypeLength; ++_j) {_o.StageEnterCostType.Add(TableEncryptionService.Convert(this.StageEnterCostType(_j), key));}
    _o.StageEnterCostId = new List<long>();
    for (var _j = 0; _j < this.StageEnterCostIdLength; ++_j) {_o.StageEnterCostId.Add(TableEncryptionService.Convert(this.StageEnterCostId(_j), key));}
    _o.StageEnterCostAmount = new List<int>();
    for (var _j = 0; _j < this.StageEnterCostAmountLength; ++_j) {_o.StageEnterCostAmount.Add(TableEncryptionService.Convert(this.StageEnterCostAmount(_j), key));}
    _o.GroundId = TableEncryptionService.Convert(this.GroundId, key);
    _o.StarGoal = new List<Plana.FlatData.StarGoalType>();
    for (var _j = 0; _j < this.StarGoalLength; ++_j) {_o.StarGoal.Add(TableEncryptionService.Convert(this.StarGoal(_j), key));}
    _o.StarGoalAmount = new List<int>();
    for (var _j = 0; _j < this.StarGoalAmountLength; ++_j) {_o.StarGoalAmount.Add(TableEncryptionService.Convert(this.StarGoalAmount(_j), key));}
    _o.StageTopography_ = TableEncryptionService.Convert(this.StageTopography_, key);
    _o.RecommandLevel = TableEncryptionService.Convert(this.RecommandLevel, key);
    _o.StageRewardId = TableEncryptionService.Convert(this.StageRewardId, key);
    _o.PlayTimeLimitInSeconds = TableEncryptionService.Convert(this.PlayTimeLimitInSeconds, key);
    _o.BattleRewardExp = TableEncryptionService.Convert(this.BattleRewardExp, key);
    _o.BattleRewardPlayerExp = TableEncryptionService.Convert(this.BattleRewardPlayerExp, key);
    _o.GroupBuffID = new List<long>();
    for (var _j = 0; _j < this.GroupBuffIDLength; ++_j) {_o.GroupBuffID.Add(TableEncryptionService.Convert(this.GroupBuffID(_j), key));}
    _o.EchelonExtensionType_ = TableEncryptionService.Convert(this.EchelonExtensionType_, key);
  }
  public static Offset<Plana.FlatData.WeekDungeonExcel> Pack(FlatBufferBuilder builder, WeekDungeonExcelT _o) {
    if (_o == null) return default(Offset<Plana.FlatData.WeekDungeonExcel>);
    var _StageEnterCostType = default(VectorOffset);
    if (_o.StageEnterCostType != null) {
      var __StageEnterCostType = _o.StageEnterCostType.ToArray();
      _StageEnterCostType = CreateStageEnterCostTypeVector(builder, __StageEnterCostType);
    }
    var _StageEnterCostId = default(VectorOffset);
    if (_o.StageEnterCostId != null) {
      var __StageEnterCostId = _o.StageEnterCostId.ToArray();
      _StageEnterCostId = CreateStageEnterCostIdVector(builder, __StageEnterCostId);
    }
    var _StageEnterCostAmount = default(VectorOffset);
    if (_o.StageEnterCostAmount != null) {
      var __StageEnterCostAmount = _o.StageEnterCostAmount.ToArray();
      _StageEnterCostAmount = CreateStageEnterCostAmountVector(builder, __StageEnterCostAmount);
    }
    var _StarGoal = default(VectorOffset);
    if (_o.StarGoal != null) {
      var __StarGoal = _o.StarGoal.ToArray();
      _StarGoal = CreateStarGoalVector(builder, __StarGoal);
    }
    var _StarGoalAmount = default(VectorOffset);
    if (_o.StarGoalAmount != null) {
      var __StarGoalAmount = _o.StarGoalAmount.ToArray();
      _StarGoalAmount = CreateStarGoalAmountVector(builder, __StarGoalAmount);
    }
    var _GroupBuffID = default(VectorOffset);
    if (_o.GroupBuffID != null) {
      var __GroupBuffID = _o.GroupBuffID.ToArray();
      _GroupBuffID = CreateGroupBuffIDVector(builder, __GroupBuffID);
    }
    return CreateWeekDungeonExcel(
      builder,
      _o.StageId,
      _o.WeekDungeonType_,
      _o.Difficulty,
      _o.BattleDuration,
      _o.PrevStageId,
      _StageEnterCostType,
      _StageEnterCostId,
      _StageEnterCostAmount,
      _o.GroundId,
      _StarGoal,
      _StarGoalAmount,
      _o.StageTopography_,
      _o.RecommandLevel,
      _o.StageRewardId,
      _o.PlayTimeLimitInSeconds,
      _o.BattleRewardExp,
      _o.BattleRewardPlayerExp,
      _GroupBuffID,
      _o.EchelonExtensionType_);
  }
}

public class WeekDungeonExcelT
{
  public long StageId { get; set; }
  public Plana.FlatData.WeekDungeonType WeekDungeonType_ { get; set; }
  public int Difficulty { get; set; }
  public long BattleDuration { get; set; }
  public long PrevStageId { get; set; }
  public List<Plana.FlatData.ParcelType> StageEnterCostType { get; set; }
  public List<long> StageEnterCostId { get; set; }
  public List<int> StageEnterCostAmount { get; set; }
  public int GroundId { get; set; }
  public List<Plana.FlatData.StarGoalType> StarGoal { get; set; }
  public List<int> StarGoalAmount { get; set; }
  public Plana.FlatData.StageTopography StageTopography_ { get; set; }
  public long RecommandLevel { get; set; }
  public long StageRewardId { get; set; }
  public long PlayTimeLimitInSeconds { get; set; }
  public long BattleRewardExp { get; set; }
  public long BattleRewardPlayerExp { get; set; }
  public List<long> GroupBuffID { get; set; }
  public Plana.FlatData.EchelonExtensionType EchelonExtensionType_ { get; set; }

  public WeekDungeonExcelT() {
    this.StageId = 0;
    this.WeekDungeonType_ = Plana.FlatData.WeekDungeonType.None;
    this.Difficulty = 0;
    this.BattleDuration = 0;
    this.PrevStageId = 0;
    this.StageEnterCostType = null;
    this.StageEnterCostId = null;
    this.StageEnterCostAmount = null;
    this.GroundId = 0;
    this.StarGoal = null;
    this.StarGoalAmount = null;
    this.StageTopography_ = Plana.FlatData.StageTopography.Street;
    this.RecommandLevel = 0;
    this.StageRewardId = 0;
    this.PlayTimeLimitInSeconds = 0;
    this.BattleRewardExp = 0;
    this.BattleRewardPlayerExp = 0;
    this.GroupBuffID = null;
    this.EchelonExtensionType_ = Plana.FlatData.EchelonExtensionType.Base;
  }
}


static public class WeekDungeonExcelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*StageId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*WeekDungeonType_*/, 4 /*Plana.FlatData.WeekDungeonType*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Difficulty*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 10 /*BattleDuration*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*PrevStageId*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 14 /*StageEnterCostType*/, 4 /*Plana.FlatData.ParcelType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*StageEnterCostId*/, 8 /*long*/, false)
      && verifier.VerifyVectorOfData(tablePos, 18 /*StageEnterCostAmount*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 20 /*GroundId*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 22 /*StarGoal*/, 4 /*Plana.FlatData.StarGoalType*/, false)
      && verifier.VerifyVectorOfData(tablePos, 24 /*StarGoalAmount*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 26 /*StageTopography_*/, 4 /*Plana.FlatData.StageTopography*/, 4, false)
      && verifier.VerifyField(tablePos, 28 /*RecommandLevel*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 30 /*StageRewardId*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 32 /*PlayTimeLimitInSeconds*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 34 /*BattleRewardExp*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 36 /*BattleRewardPlayerExp*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 38 /*GroupBuffID*/, 8 /*long*/, false)
      && verifier.VerifyField(tablePos, 40 /*EchelonExtensionType_*/, 4 /*Plana.FlatData.EchelonExtensionType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
