// <auto-generated>
//  automatically generated by the PlanaBuffers compiler, do not modify
//PlanaBuffer. Custom Flatbuff Compiler
// </auto-generated>

namespace Plana.FlatData
{

public enum WeekDungeonType : int
{
  None = 0,
  ChaserA = 1,
  ChaserB = 2,
  ChaserC = 3,
  FindGift = 4,
  Blood = 5,
};


}
